using System.Text.Json;
using System.Text.Json.Serialization;
using VulcansTrace.Linux.Core;

namespace VulcansTrace.Linux.Evidence;

/// <summary>
/// Builds MITRE ATT&CK Navigator layer JSON from security findings.
/// </summary>
/// <remarks>
/// Produces a layer compatible with MITRE's official ATT&CK Navigator:
/// https://github.com/mitre-attack/attack-navigator/blob/master/layers/LAYERFORMATv4_5.md
/// </remarks>
public sealed class MitreLayerBuilder
{
    private readonly string _layerVersion;
    private readonly string _navigatorVersion;
    private readonly string _attackVersion;
    private const string Domain = "enterprise-attack";

    /// <summary>
    /// Initializes a new instance of the <see cref="MitreLayerBuilder"/> class.
    /// </summary>
    /// <param name="attackVersion">MITRE ATT&CK version (default: 16).</param>
    /// <param name="navigatorVersion">Navigator version (default: 4.9.5).</param>
    /// <param name="layerVersion">Layer format version (default: 4.5).</param>
    public MitreLayerBuilder(string? attackVersion = null, string? navigatorVersion = null, string? layerVersion = null)
    {
        _attackVersion = attackVersion ?? "16";
        _navigatorVersion = navigatorVersion ?? "4.9.5";
        _layerVersion = layerVersion ?? "4.5";
    }

    /// <summary>
    /// Builds a Navigator layer from analysis findings.
    /// </summary>
    /// <param name="findings">The findings to map.</param>
    /// <param name="name">Optional layer name.</param>
    /// <returns>JSON string representing the layer.</returns>
    public string BuildLayer(IReadOnlyList<Finding> findings, string? name = null)
    {
        return BuildCoverageLayer(Array.Empty<MitreCoverageSource>(), findings, name);
    }

    /// <summary>
    /// Builds a Navigator coverage layer from mapped sources and observed findings.
    /// </summary>
    /// <param name="coverageSources">Detector and rule mappings that define VulcansTrace coverage.</param>
    /// <param name="findings">Observed findings used to score covered techniques.</param>
    /// <param name="name">Optional layer name.</param>
    /// <returns>JSON string representing the layer.</returns>
    public string BuildCoverageLayer(
        IReadOnlyList<MitreCoverageSource> coverageSources,
        IReadOnlyList<Finding> findings,
        string? name = null)
    {
        ArgumentNullException.ThrowIfNull(coverageSources);
        ArgumentNullException.ThrowIfNull(findings);

        var techniques = AggregateTechniques(coverageSources, findings);

        var layer = new MitreLayer
        {
            Name = name ?? $"VulcansTrace Coverage - {DateTime.UtcNow:yyyy-MM-dd}",
            Versions = new MitreLayerVersions
            {
                Attack = _attackVersion,
                Navigator = _navigatorVersion,
                Layer = _layerVersion
            },
            Domain = Domain,
            Description = $"Coverage layer generated by VulcansTrace Linux Edition. Mapped {coverageSources.Count} coverage source(s) and {findings.Count} observed finding(s) to {techniques.Count} MITRE ATT&CK technique cell(s).",
            Techniques = techniques,
            Gradient = new MitreGradient
            {
                Colors = new[] { "#d8f3dc", "#1f77b4" },
                MinValue = 0,
                MaxValue = 10
            },
            ShowTacticRowBackground = true,
            Sorting = 0
        };

        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
        };

        return JsonSerializer.Serialize(layer, options);
    }

    private static List<MitreLayerTechnique> AggregateTechniques(
        IReadOnlyList<MitreCoverageSource> coverageSources,
        IReadOnlyList<Finding> findings)
    {
        var byTechnique = new Dictionary<MitreTechniqueKey, MitreTechniqueAggregate>();

        foreach (var source in coverageSources)
        {
            foreach (var technique in source.MitreTechniques)
            {
                var aggregate = GetOrCreateAggregate(byTechnique, technique);
                var sourceText = $"{source.SourceType}: {source.SourceId} - {source.SourceName}";

                if (aggregate.CoverageSources.Add(sourceText))
                {
                    aggregate.Metadata.Add(new MitreTechniqueMetadata
                    {
                        Name = "Coverage",
                        Value = sourceText
                    });
                }

                AddWhy(aggregate, technique);
            }
        }

        foreach (var finding in findings)
        {
            foreach (var technique in finding.MitreTechniques)
            {
                var aggregate = GetOrCreateAggregate(byTechnique, technique);
                aggregate.ObservedCount++;

                var source = string.IsNullOrEmpty(finding.RuleId)
                    ? $"[{finding.Category}] {finding.ShortDescription}"
                    : $"[{finding.RuleId}] {finding.ShortDescription}";

                if (aggregate.ObservedSources.Add(source))
                {
                    aggregate.Metadata.Add(new MitreTechniqueMetadata
                    {
                        Name = "Observed Finding",
                        Value = source
                    });
                }

                AddWhy(aggregate, technique);
            }
        }

        var result = new List<MitreLayerTechnique>(byTechnique.Count);

        foreach (var (key, aggregate) in byTechnique
            .OrderBy(k => k.Key.TechniqueId, StringComparer.Ordinal)
            .ThenBy(k => k.Key.Tactic ?? string.Empty, StringComparer.Ordinal))
        {
            var comments = new List<string>();
            comments.AddRange(aggregate.CoverageSources.OrderBy(s => s, StringComparer.Ordinal).Select(s => $"Covered by {s}"));
            comments.AddRange(aggregate.ObservedSources.OrderBy(s => s, StringComparer.Ordinal).Select(s => $"Observed in {s}"));
            comments.AddRange(aggregate.WhyTexts.OrderBy(s => s, StringComparer.Ordinal).Select(w => $"Why: {w}"));

            result.Add(new MitreLayerTechnique
            {
                TechniqueId = key.TechniqueId,
                Tactic = key.Tactic,
                Score = Math.Min(aggregate.ObservedCount, 10),
                Comment = string.Join(" | ", comments.Take(5)),
                Enabled = true,
                Metadata = aggregate.Metadata.Take(10).ToList()
            });
        }

        return result;
    }

    private static MitreTechniqueAggregate GetOrCreateAggregate(
        Dictionary<MitreTechniqueKey, MitreTechniqueAggregate> byTechnique,
        MitreTechnique technique)
    {
        var key = new MitreTechniqueKey(technique.TechniqueId, ToNavigatorTactic(technique.Tactic));
        if (!byTechnique.TryGetValue(key, out var aggregate))
        {
            aggregate = new MitreTechniqueAggregate();
            byTechnique[key] = aggregate;
        }

        return aggregate;
    }

    private static void AddWhy(MitreTechniqueAggregate aggregate, MitreTechnique technique)
    {
        if (!string.IsNullOrWhiteSpace(technique.WhyItMatters))
        {
            aggregate.WhyTexts.Add(technique.WhyItMatters);
        }
    }

    private static string? ToNavigatorTactic(string tactic)
    {
        if (string.IsNullOrWhiteSpace(tactic))
            return null;

        return tactic.Trim() switch
        {
            "Reconnaissance" => "reconnaissance",
            "Resource Development" => "resource-development",
            "Initial Access" => "initial-access",
            "Execution" => "execution",
            "Persistence" => "persistence",
            "Privilege Escalation" => "privilege-escalation",
            "Defense Evasion" => "defense-evasion",
            "Credential Access" => "credential-access",
            "Discovery" => "discovery",
            "Lateral Movement" => "lateral-movement",
            "Collection" => "collection",
            "Command and Control" => "command-and-control",
            "Exfiltration" => "exfiltration",
            "Impact" => "impact",
            var value => value.ToLowerInvariant().Replace(' ', '-')
        };
    }
}

internal sealed class MitreTechniqueAggregate
{
    public int ObservedCount { get; set; }
    public HashSet<string> CoverageSources { get; } = new(StringComparer.Ordinal);
    public HashSet<string> ObservedSources { get; } = new(StringComparer.Ordinal);
    public HashSet<string> WhyTexts { get; } = new(StringComparer.Ordinal);
    public List<MitreTechniqueMetadata> Metadata { get; } = new();
}

internal sealed record MitreTechniqueKey(string TechniqueId, string? Tactic);

internal sealed class MitreLayer
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("versions")]
    public MitreLayerVersions Versions { get; set; } = new();

    [JsonPropertyName("domain")]
    public string Domain { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("techniques")]
    public List<MitreLayerTechnique> Techniques { get; set; } = new();

    [JsonPropertyName("gradient")]
    public MitreGradient Gradient { get; set; } = new();

    [JsonPropertyName("showTacticRowBackground")]
    public bool ShowTacticRowBackground { get; set; }

    [JsonPropertyName("sorting")]
    public int Sorting { get; set; }
}

internal sealed class MitreLayerVersions
{
    [JsonPropertyName("attack")]
    public string Attack { get; set; } = string.Empty;

    [JsonPropertyName("navigator")]
    public string Navigator { get; set; } = string.Empty;

    [JsonPropertyName("layer")]
    public string Layer { get; set; } = string.Empty;
}

internal sealed class MitreLayerTechnique
{
    [JsonPropertyName("techniqueID")]
    public string TechniqueId { get; set; } = string.Empty;

    [JsonPropertyName("tactic")]
    public string? Tactic { get; set; }

    [JsonPropertyName("score")]
    public int Score { get; set; }

    [JsonPropertyName("comment")]
    public string Comment { get; set; } = string.Empty;

    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    [JsonPropertyName("metadata")]
    public List<MitreTechniqueMetadata> Metadata { get; set; } = new();
}

internal sealed class MitreTechniqueMetadata
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("value")]
    public string Value { get; set; } = string.Empty;
}

internal sealed class MitreGradient
{
    [JsonPropertyName("colors")]
    public string[] Colors { get; set; } = Array.Empty<string>();

    [JsonPropertyName("minValue")]
    public int MinValue { get; set; }

    [JsonPropertyName("maxValue")]
    public int MaxValue { get; set; }
}
