namespace VulcansTrace.Linux.Agent.Reports;

/// <summary>
/// Describes the kind of active countermeasure generated by the incident response playbook.
/// </summary>
public enum CountermeasureType
{
    /// <summary>Firewall DROP rule (iptables / nftables).</summary>
    IptablesDrop,

    /// <summary>Auditd monitoring rule for the compromised host.</summary>
    AuditdMonitor
}
